// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zxlccvozsbjmwrjbwyrr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4bGNjdm96c2JqbXdyamJ3eXJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5MDc3MzYsImV4cCI6MjA3MzQ4MzczNn0.g76X2TVsCsT-ntssunqsQxUt4exVUXnQzPnan3hhMn0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});